# -*- coding: utf-8 -*-
"""aprior_algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yanBkWl6d07Cl4crbs6G4CAsdKjlBZCY
"""

import pandas as pd
from itertools import combinations

# Sample transaction dataset
transactions = [
    ['Milk', 'Bread'],
    ['Milk', 'Diaper', 'Beer', 'Eggs'],
    ['Milk', 'Diaper', 'Beer', 'Cola'],
    ['Bread', 'Milk', 'Diaper', 'Beer'],
    ['Bread', 'Milk', 'Diaper', 'Cola']
]

min_support = 0.4
min_confidence = 0.6

# Convert transactions into list of sets
transaction_list = list(map(set, transactions))
total_transactions = len(transaction_list)

# Function to calculate support
def get_support(itemset):
    count = 0
    for t in transaction_list:
        if itemset.issubset(t):
            count += 1
    return count / total_transactions

# Step 1: Get unique items
unique_items = set()
for t in transaction_list:
    unique_items.update(t)

# Step 2: Generate frequent itemsets
frequent_itemsets = {}

for r in range(1, len(unique_items) + 1):
    for combo in combinations(unique_items, r):
        itemset = set(combo)
        support = get_support(itemset)

        if support >= min_support:
            frequent_itemsets[frozenset(itemset)] = support

# Display Frequent Itemsets
print("\nFrequent Itemsets:")
freq_data = []

for itemset, support in frequent_itemsets.items():
    freq_data.append([list(itemset), support])

freq_df = pd.DataFrame(
    freq_data,
    columns=["Itemset", "Support"]
)

print(freq_df)

# Step 3: Generate Association Rules
rules_list = []

for itemset in frequent_itemsets:
    if len(itemset) > 1:

        for i in range(1, len(itemset)):
            subsets = combinations(itemset, i)

            for antecedent in subsets:
                antecedent = frozenset(antecedent)
                consequent = itemset - antecedent

                support_itemset = frequent_itemsets[itemset]
                support_antecedent = frequent_itemsets[antecedent]
                support_consequent = frequent_itemsets.get(
                    consequent, 0
                )

                confidence = (
                    support_itemset /
                    support_antecedent
                )

                if support_consequent > 0:
                    lift = (
                        confidence /
                        support_consequent
                    )
                else:
                    lift = 0

                if confidence >= min_confidence:
                    rules_list.append([
                        list(antecedent),
                        list(consequent),
                        support_itemset,
                        confidence,
                        lift
                    ])

# Display Association Rules
print("\nAssociation Rules:")

rules_df = pd.DataFrame(
    rules_list,
    columns=[
        "Antecedent",
        "Consequent",
        "Support",
        "Confidence",
        "Lift"
    ]
)

print(rules_df)

